/***************************  WORKFLOW DEFINITIONS  ***************************/

export const WORKFLOWS = [
  // ── LAUNCH ──────────────────────────────────────────────
  {
    id: 'google_search_launch',
    title: 'Google Search Ads',
    section: 'launch',
    platform: 'google',
    description: 'Launch Google Search campaigns with AI-optimised headlines, descriptions & keyword groups',
    iconImage: '/images/icons/marketing-strategy-3d.png',
    inputSchema: [
      { key: 'account_id', label: 'Google Ads Account', type: 'account_select', platform: 'google', required: true },
      { key: 'goal', label: 'Goal', type: 'select', required: true, options: ['Leads', 'Sales', 'Traffic'] },
      { key: 'website_url', label: 'Website URL', type: 'text', required: true, placeholder: 'https://yoursite.com' },
      { key: 'daily_budget', label: 'Daily Budget ($)', type: 'number', required: true, placeholder: '50' },
      { key: 'geo', label: 'Target Location', type: 'text', required: true, placeholder: 'United States' },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'meta_campaign_launch',
    title: 'Meta Campaign',
    section: 'launch',
    platform: 'meta',
    description: 'Create Facebook & Instagram campaigns — ad sets, audiences, creatives & budget allocation',
    iconImage: '/images/icons/facebook-3d.png',
    inputSchema: [
      { key: 'account_id', label: 'Meta Ad Account', type: 'account_select', platform: 'meta', required: true },
      { key: 'objective', label: 'Objective', type: 'select', required: true, options: ['Conversions', 'Traffic', 'Leads', 'Brand Awareness'] },
      { key: 'page_url', label: 'Page / Landing URL', type: 'text', required: true, placeholder: 'https://yoursite.com/offer' },
      { key: 'daily_budget', label: 'Daily Budget ($)', type: 'number', required: true, placeholder: '50' },
      { key: 'audience_interests', label: 'Target Interests', type: 'text', required: false, placeholder: 'e.g. fitness, nutrition' },
      { key: 'geo', label: 'Target Location', type: 'text', required: true, placeholder: 'United States' },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },

  // ── OPTIMISE ────────────────────────────────────────────
  {
    id: 'ab_test_generator',
    title: 'A/B Test Generator',
    section: 'optimise',
    platform: 'both',
    description: 'Generate statistically sound A/B test variations for headlines, images, audiences & landing pages',
    iconImage: '/images/icons/ab-testing-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'campaign_id', label: 'Campaign ID', type: 'text', required: true, placeholder: 'e.g. 123456789' },
      { key: 'test_element', label: 'Test Element', type: 'select', required: true, options: ['Headlines', 'Images', 'Audiences', 'Landing Pages'] },
      { key: 'variations', label: 'Number of Variations', type: 'number', required: true, default: 3 },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'bid_optimisation',
    title: 'Bid Optimisation',
    section: 'optimise',
    platform: 'both',
    description: 'AI analyses your campaign data to recommend optimal bidding strategies and budget allocation',
    iconImage: '/images/icons/data-analytic-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'date_range', label: 'Date Range', type: 'select', required: true, options: ['7d', '14d', '30d'] },
      { key: 'target_cpa', label: 'Target CPA ($)', type: 'number', required: false, placeholder: '25' },
      { key: 'target_roas', label: 'Target ROAS', type: 'number', required: false, placeholder: '3.0' },
      { key: 'min_conversions', label: 'Min Conversions', type: 'number', required: false, default: 5 },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'creative_refresh',
    title: 'Creative Refresh',
    section: 'optimise',
    platform: 'both',
    description: "Detect ad fatigue and generate fresh creative variations while preserving what's working",
    iconImage: '/images/icons/copywriting-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'fatigue_threshold', label: 'Fatigue Threshold (days)', type: 'number', required: true, default: 14 },
      { key: 'preserve_top_n', label: 'Keep Top N Creatives', type: 'number', required: false, default: 3 },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'audience_expansion',
    title: 'Audience Expansion',
    section: 'optimise',
    platform: 'both',
    description: 'Discover new high-value audience segments based on your best performers and market data',
    iconImage: '/images/icons/social-media-engagement-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'seed_audience', label: 'Seed Audience / Segment', type: 'text', required: false, placeholder: 'e.g. Lookalike 1% Purchasers' },
      { key: 'budget_limit', label: 'Budget Limit ($)', type: 'number', required: false, placeholder: '500' },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },

  // ── SCALE ───────────────────────────────────────────────
  {
    id: 'scale_winners',
    title: 'Scale Winners',
    section: 'scale',
    platform: 'both',
    description: 'Identify top-performing campaigns and get an AI scaling plan with budget & targeting adjustments',
    iconImage: '/images/icons/promotion-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'date_range', label: 'Date Range', type: 'select', required: true, options: ['7d', '14d', '30d'] },
      { key: 'budget_increase', label: 'Max Budget Increase (%)', type: 'number', required: true, default: 25 },
      { key: 'min_roas', label: 'Min ROAS to Scale', type: 'number', required: false, placeholder: '2.0' },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'kill_underperformers',
    title: 'Kill Underperformers',
    section: 'scale',
    platform: 'both',
    description: 'Identify and pause wasted spend — ads, keywords & audiences bleeding your budget',
    iconImage: '/images/icons/optimization-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'date_range', label: 'Date Range', type: 'select', required: true, options: ['7d', '14d', '30d'] },
      { key: 'max_cpa', label: 'Max Acceptable CPA ($)', type: 'number', required: false, placeholder: '50' },
      { key: 'min_spend', label: 'Min Spend to Evaluate ($)', type: 'number', required: false, default: 10 },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'retargeting_setup',
    title: 'Retargeting Setup',
    section: 'scale',
    platform: 'both',
    description: 'Build multi-touchpoint retargeting funnels across platforms with optimal frequency caps',
    iconImage: '/images/icons/backlink-3d.png',
    inputSchema: [
      { key: 'platform', label: 'Platform', type: 'select', required: true, options: ['google', 'meta', 'both'] },
      { key: 'account_id', label: 'Ad Account', type: 'account_select', required: true },
      { key: 'pixel_id', label: 'Pixel / Tag ID', type: 'text', required: false, placeholder: 'e.g. 123456789012345' },
      { key: 'audience_window', label: 'Audience Window', type: 'select', required: true, options: ['7 days', '14 days', '30 days', '60 days', '90 days'] },
      { key: 'daily_budget', label: 'Daily Budget ($)', type: 'number', required: true, placeholder: '25' },
      { key: 'dry_run', label: 'Dry run (preview only)', type: 'boolean', default: true },
    ],
  },
  {
    id: 'cross_platform_report',
    title: 'Cross-Platform Report',
    section: 'scale',
    platform: 'both',
    description: 'Unified performance report across Google, Meta & Instagram with AI insights and recommendations',
    iconImage: '/images/icons/data-analytic-3d.png',
    inputSchema: [
      { key: 'account_id', label: 'Primary Ad Account', type: 'account_select', required: true },
      { key: 'date_range', label: 'Date Range', type: 'select', required: true, options: ['7d', '14d', '30d', '90d'] },
      { key: 'include_google', label: 'Include Google Ads', type: 'boolean', default: true },
      { key: 'include_meta', label: 'Include Meta Ads', type: 'boolean', default: true },
      { key: 'compare_period', label: 'Compare to Previous Period', type: 'boolean', default: true },
    ],
  },
];

// Platform label + color helpers
export const PLATFORM_CONFIG = {
  google: { label: 'Google', color: '#4285F4' },
  meta: { label: 'Meta', color: '#0668E1' },
  both: { label: 'All Platforms', color: '#805AF5' },
};
