overrides:
  qs: ^6.16.0
allowBuilds:
  esbuild: true
  lightningcss: true
  '@firebase/util': true
  protobufjs: true
  '@mui/x-telemetry': false
  core-js: true
  fsevents: true
minimumReleaseAge: 1440
